version: '3.8'

services:
  # Servicio de Base de Datos
  db:
    image: postgres:15
    container_name: citylens_db
    restart: always

    environment:
      POSTGRES_USER: user_admin
      POSTGRES_PASSWORD: password_seguro
      POSTGRES_DB: citylens_db

    ports:
      - "5432:5432"

    volumes:
      # Volumen nombrado manejado por Docker
      - postgres_data:/var/lib/postgresql/data

  # Servicio de tu aplicación Flask
  web:
    build: .
    container_name: citylens_app
    restart: always

    ports:
      - "5000:5000"

    environment:
      # Conexión interna entre contenedores
      DATABASE_URL: postgresql://user_admin:password_seguro@db:5432/citylens_db

      FLASK_ENV: development
      ORIGEN_PERMITIDO: http://localhost:5000

    depends_on:
      - db

    volumes:
      # Monta tu proyecto dentro del contenedor
      # para reflejar cambios en tiempo real
      - .:/app

# Declaración del volumen nombrado
volumes:
  postgres_data: