version: '3.8'

services:
  db:
    image: postgres:15
    container_name: citylens_db
    restart: always

    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}

    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"

    volumes:
      - postgres_data:/var/lib/postgresql/data

  web:
    build: .
    container_name: citylens_app
    restart: always

    ports:
      - "${FLASK_PORT}:${FLASK_PORT}"

    environment:
      DATABASE_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:${POSTGRES_PORT}/${POSTGRES_DB}
      FLASK_ENV: ${FLASK_ENV}
      ORIGEN_PERMITIDO: ${ORIGEN_PERMITIDO}

    depends_on:
      - db

    # Montaje de código solo en desarrollo
    volumes:
      - type: bind
        source: .
        target: /app
        consistency: cached
        # Solo se aplica si estamos en dev (override)

volumes:
  postgres_data: