"""Add BBox columns to City model

Revision ID: 31516834e7dd
Revises: 81505e21346b
Create Date: 2026-05-01 16:12:44.926229

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '31516834e7dd'
down_revision = '81505e21346b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cities', schema=None) as batch_op:
        batch_op.add_column(sa.Column('bbox_south', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('bbox_north', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('bbox_west', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('bbox_east', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cities', schema=None) as batch_op:
        batch_op.drop_column('bbox_east')
        batch_op.drop_column('bbox_west')
        batch_op.drop_column('bbox_north')
        batch_op.drop_column('bbox_south')

    # ### end Alembic commands ###
