"""Initial migration

Revision ID: 41d3fa834cdb
Revises: 
Create Date: 2026-04-29 16:11:43.137444

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '41d3fa834cdb'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('places', schema=None) as batch_op:
        batch_op.add_column(sa.Column('osm_place_id', sa.String(length=255), nullable=True))
        batch_op.drop_constraint(batch_op.f('places_google_place_id_key'), type_='unique')
        batch_op.create_unique_constraint(None, ['osm_place_id'])
        batch_op.drop_column('google_place_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('places', schema=None) as batch_op:
        batch_op.add_column(sa.Column('google_place_id', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='unique')
        batch_op.create_unique_constraint(batch_op.f('places_google_place_id_key'), ['google_place_id'], postgresql_nulls_not_distinct=False)
        batch_op.drop_column('osm_place_id')

    # ### end Alembic commands ###
