"""Enriquecer modelo City

Revision ID: 81505e21346b
Revises: ee7b3fd10ff0
Create Date: 2026-05-01 05:22:08.164332

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '81505e21346b'
down_revision = 'ee7b3fd10ff0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cities', schema=None) as batch_op:
        batch_op.add_column(sa.Column('iso_code', sa.String(length=5), nullable=True))
        batch_op.add_column(sa.Column('flag_url', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('capital', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('lat', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('lon', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cities', schema=None) as batch_op:
        batch_op.drop_column('lon')
        batch_op.drop_column('lat')
        batch_op.drop_column('capital')
        batch_op.drop_column('flag_url')
        batch_op.drop_column('iso_code')

    # ### end Alembic commands ###
