"""Agregar campos enriquecidos a Place

Revision ID: ee7b3fd10ff0
Revises: 9cf1ccd14ad5
Create Date: 2026-05-01 02:48:47.968675

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = 'ee7b3fd10ff0'
down_revision = '9cf1ccd14ad5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('places', schema=None) as batch_op:
        batch_op.add_column(sa.Column('website', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('phone', sa.String(length=50), nullable=True))
        batch_op.alter_column('opening_hours',
               existing_type=postgresql.JSON(astext_type=sa.Text()),
               type_=sa.String(length=255),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('places', schema=None) as batch_op:
        batch_op.alter_column('opening_hours',
               existing_type=sa.String(length=255),
               type_=postgresql.JSON(astext_type=sa.Text()),
               existing_nullable=True)
        batch_op.drop_column('phone')
        batch_op.drop_column('website')

    # ### end Alembic commands ###
